"""Generate the map registry in several formats for external reuse.

The source of truth is ``data/maps.yaml`` (minimal: ``lon_0/x_0/y_0`` per map).
``generate()`` expands it to the *full* projection parameters and writes, into a
chosen directory, the same data in four formats so anyone can pick what fits:

- ``maps.yaml`` — full params, YAML.
- ``maps.json`` — full params, JSON (GIS / proj4 / any language).
- ``maps.md``   — human-readable table + the full PROJ strings.
- ``maps.py``   — a standalone ``MAPS`` dict (+ ``PROJ4``), no dependencies.

Each record is self-contained and includes the assembled ``proj4`` string.
"""

from __future__ import annotations

import json
from pathlib import Path

import yaml

from .maps import available_maps, full_params

_NOTE = "Generated by `dcs-coords generate` from src/dcs_coords/data/maps.yaml — do not edit by hand."


def build_registry() -> dict[str, dict]:
    """Full parameters for every known map, keyed by (sorted) map name."""
    return {name: full_params(name) for name in available_maps()}


def to_json(registry: dict[str, dict]) -> str:
    return json.dumps(registry, indent=2, ensure_ascii=False) + "\n"


def to_yaml(registry: dict[str, dict]) -> str:
    body = yaml.safe_dump(registry, sort_keys=False, default_flow_style=False, allow_unicode=True)
    return f"# {_NOTE}\n{body}"


# The Map class is static (the f-string braces below are literal text in the
# generated file, not evaluated here).
_MAP_CLASS_SRC = '''from dataclasses import dataclass


@dataclass(frozen=True)
class Map:
    """A DCS map's Transverse Mercator projection (WGS84).

    Only ``name``/``lon_0``/``x_0``/``y_0`` vary between maps; the rest is the
    fixed model shared by every DCS map (kept as defaults). ``proj4`` is the
    assembled PROJ string, ready for pyproj / GDAL / proj4js.
    """

    name: str
    lon_0: int  # central meridian (degrees)
    x_0: float  # false easting (m)
    y_0: float  # false northing (m)
    proj: str = "tmerc"
    lat_0: int = 0
    k_0: float = 0.9996
    towgs84: str = "0,0,0,0,0,0,0"
    units: str = "m"
    vunits: str = "m"
    ellps: str = "WGS84"
    no_defs: bool = True
    axis: str = "neu"

    @property
    def proj4(self) -> str:
        return (
            f"+proj={self.proj} +lat_0={self.lat_0} +lon_0={self.lon_0} "
            f"+k_0={self.k_0} +x_0={self.x_0} +y_0={self.y_0} "
            f"+towgs84={self.towgs84} +units={self.units} +vunits={self.vunits} "
            f"+ellps={self.ellps} +no_defs +axis={self.axis}"
        )
'''


def to_python(registry: dict[str, dict]) -> str:
    lines = [
        '"""DCS map projection parameters.',
        "",
        _NOTE,
        '"""',
        "",
        _MAP_CLASS_SRC,
        "",
        "MAPS: list[Map] = [",
    ]
    for name, p in registry.items():
        lines.append(
            f"    Map(name={name!r}, lon_0={p['lon_0']!r}, "
            f"x_0={p['x_0']!r}, y_0={p['y_0']!r}),"
        )
    lines += [
        "]",
        "",
        "MAPS_BY_NAME: dict[str, Map] = {m.name: m for m in MAPS}",
        "",
    ]
    return "\n".join(lines)


def to_markdown(registry: dict[str, dict]) -> str:
    lines = [
        "# DCS map projection parameters",
        "",
        f"_{_NOTE}_",
        "",
        "All maps share the same Transverse Mercator model on WGS84: "
        "`proj=tmerc`, `lat_0=0`, `k_0=0.9996`, `ellps=WGS84`, "
        "`towgs84=0,0,0,0,0,0,0`, `units=m`, `vunits=m`, `axis=neu`, `no_defs`. "
        "Only `lon_0`, `x_0` and `y_0` vary:",
        "",
        "| Map | lon_0 | x_0 (false easting) | y_0 (false northing) |",
        "|-----|------:|--------------------:|---------------------:|",
    ]
    for name, p in registry.items():
        lines.append(f"| {name} | {p['lon_0']} | {p['x_0']:.6f} | {p['y_0']:.6f} |")
    lines += ["", "## Full PROJ strings", ""]
    for name, p in registry.items():
        lines.append(f"- **{name}**: `{p['proj4']}`")
    return "\n".join(lines) + "\n"


_WRITERS = {
    "maps.yaml": to_yaml,
    "maps.json": to_json,
    "maps.md": to_markdown,
    "maps.py": to_python,
}


def generate(out_dir: str | Path) -> list[Path]:
    """Write all formats into ``out_dir`` and return the written paths."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    registry = build_registry()
    written = []
    for filename, writer in _WRITERS.items():
        path = out / filename
        path.write_text(writer(registry), encoding="utf-8")
        written.append(path)
    return written
