"""DCS map projection parameters.

Generated by `dcs-coords generate` from src/dcs_coords/data/maps.yaml — do not edit by hand.
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class Map:
    """A DCS map's Transverse Mercator projection (WGS84).

    Only ``name``/``lon_0``/``x_0``/``y_0`` vary between maps; the rest is the
    fixed model shared by every DCS map (kept as defaults). ``proj4`` is the
    assembled PROJ string, ready for pyproj / GDAL / proj4js.
    """

    name: str
    lon_0: int  # central meridian (degrees)
    x_0: float  # false easting (m)
    y_0: float  # false northing (m)
    proj: str = "tmerc"
    lat_0: int = 0
    k_0: float = 0.9996
    towgs84: str = "0,0,0,0,0,0,0"
    units: str = "m"
    vunits: str = "m"
    ellps: str = "WGS84"
    no_defs: bool = True
    axis: str = "neu"

    @property
    def proj4(self) -> str:
        return (
            f"+proj={self.proj} +lat_0={self.lat_0} +lon_0={self.lon_0} "
            f"+k_0={self.k_0} +x_0={self.x_0} +y_0={self.y_0} "
            f"+towgs84={self.towgs84} +units={self.units} +vunits={self.vunits} "
            f"+ellps={self.ellps} +no_defs +axis={self.axis}"
        )


MAPS: list[Map] = [
    Map(name='Afghanistan', lon_0=63, x_0=-300150.00000261003, y_0=-3759657.000001035),
    Map(name='Caucasus', lon_0=33, x_0=-99516.99999766012, y_0=-4998115.000001914),
    Map(name='Falklands', lon_0=-57, x_0=147639.99999997593, y_0=5815417.000000032),
    Map(name='GermanyCW', lon_0=21, x_0=35427.62000060154, y_0=-6061633.12800163),
    Map(name='Iraq', lon_0=45, x_0=72290.0000013377, y_0=-3680056.999997638),
    Map(name='Kola', lon_0=21, x_0=-62701.99999924752, y_0=-7543625.000001493),
    Map(name='MarianaIslands', lon_0=147, x_0=238418.00000022806, y_0=-1491839.9999989243),
    Map(name='MarianaIslandsWWII', lon_0=147, x_0=238418.00000022806, y_0=-1491839.9999989243),
    Map(name='Nevada', lon_0=-117, x_0=-193996.80999964548, y_0=-4410028.063999966),
    Map(name='Normandy', lon_0=-3, x_0=-195525.99999845505, y_0=-5484812.999999176),
    Map(name='PersianGulf', lon_0=57, x_0=75755.99999870236, y_0=-2894933.000000028),
    Map(name='SinaiMap', lon_0=33, x_0=169221.99999983577, y_0=-3325312.9999987846),
    Map(name='Syria', lon_0=39, x_0=282801.00000019063, y_0=-3879866.000000911),
    Map(name='TheChannel', lon_0=3, x_0=99376.00000000288, y_0=-5636889.00000001),
]

MAPS_BY_NAME: dict[str, Map] = {m.name: m for m in MAPS}
